<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="9.059" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2024-08-24T19:34:22" tests="0" file="cypress\e2e\features\Authentication.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Authentication" timestamp="2024-08-24T19:34:22" tests="2" time="9.056" failures="1">
    <testcase name="Authentication User can log in with valid email and password" time="2.549" classname="User can log in with valid email and password">
    </testcase>
    <testcase name="Authentication Invalid login credentials" time="0.000" classname="Invalid login credentials">
      <failure message="Timed out retrying after 4000ms: Expected to find element: `[data-test=password-input]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-test=password-input]`, but never found it.
    at Context.eval (http://localhost:5173/__cypress/tests?p=cypress\support\e2e.js:4:15)]]></failure>
    </testcase>
  </testsuite>
</testsuites>